Repository XwanXuanX/NEAT-plus-plus, pull requests merged in 2024-08, with the labels that each got.

#12 Add CMake files
  .gitignore
  CMakeLists.txt
  README.md
  inc/CMakeLists.txt
  src/CMakeLists.txt
Labels: DevOps

#16 Read from .model file
  .gitignore
  inc/genotype.hpp
  src/genotype.cpp
  src/main.cpp
Labels: New feature!

#15 Dump to .model file
  .gitignore
  CMakeLists.txt
  inc/genotype.hpp
  inc/utility.hpp
  src/CMakeLists.txt
  src/genotype.cpp
  src/main.cpp
  src/utility.cpp
Labels: New feature!

#20 Add network visualization with Graphviz
  Dockerfile
  inc/genotype.hpp
  src/genotype.cpp
  src/main.cpp
Labels: New feature!

#22 Isolating printing utilities from Genotype class
  CMakeLists.txt
  inc/genotype.hpp
  inc/prob.hpp
  src/CMakeLists.txt
  src/genotype.cpp
  src/main.cpp
  src/prob.cpp
Labels: refactor
