Repository XwanXuanX/NEAT-plus-plus, pull requests merged in 2024-09, with the labels that each got.

#28 Simple XOR validation game
  CMakeLists.txt
  inc/eval-interface.hpp
  inc/genotype.hpp
  inc/xor-game.hpp
  src/CMakeLists.txt
  src/genotype.cpp
  src/main.cpp
  src/xor-game.cpp
Labels: Test and Validation, New feature!

#27 Build evaluation and training framework for multiple tasks
  CMakeLists.txt
  inc/eval-interface.hpp
  inc/genotype.hpp
  inc/xor-game.hpp
  src/CMakeLists.txt
  src/genotype.cpp
  src/main.cpp
  src/xor-game.cpp
Labels: Test and Validation, New feature!

#35 Construct adjacency list
  inc/genotype.hpp
  src/genotype.cpp
Labels: New feature!

#39 Add new node mutation
  inc/genotype.hpp
  src/genotype.cpp
  src/main.cpp
  src/xor-game.cpp
Labels: New feature!

#38 Add random connection mutation
  inc/genotype.hpp
  inc/utility.hpp
  src/genotype.cpp
  src/main.cpp
  src/utility.cpp
  src/xor-game.cpp
Labels: New feature!, genotype

#43 Extract graph related algorithm to a seperate class
  CMakeLists.txt
  inc/gene.hpp
  inc/genotype.hpp
  inc/graph-network.hpp
  src/CMakeLists.txt
  src/gene.cpp
  src/genotype.cpp
  src/graph-network.cpp
Labels: refactor, genotype

#47 Repository updates (general)
  .github/workflows/c-cpp.yml
  CMakeLists.txt
  README.md
  doc/example-net.png
  inc/CMakeLists.txt
  src/CMakeLists.txt
  src/main.cpp
Labels: documentation, DevOps
